-- Seed data for development and offline testing

-- Operators
INSERT INTO operators (
  employee_id,
  clock_number,
  first_name,
  last_name,
  full_name,
  department,
  primary_shift,
  job_title,
  skill_level,
  cnc_certified,
  lathe_certified,
  mill_certified,
  cat536_6763_experience,
  cat536_6763_pieces_produced,
  active
) VALUES
  ('1422', 1422, 'Logan', 'Maas', 'Maas, Logan', 'Machining', 1, 'Machinist', 'Advanced', TRUE, TRUE, TRUE, TRUE, 125, TRUE),
  ('1395', 1395, 'Trevor C', 'Swalheim', 'Swalheim, Trevor C', 'Machining', 2, 'Machinist', 'Advanced', TRUE, TRUE, TRUE, TRUE, 118, TRUE)
ON CONFLICT DO NOTHING;

-- Equipment
INSERT INTO equipment (
  equipment_number,
  description,
  work_center,
  equipment_type,
  equipment_group,
  location,
  status,
  model,
  manufacturer,
  active
) VALUES
  ('CNC-450', 'Okuma Horizontal CNC', 'WC-200', 'CNC Horizontal Mill', 'Machining', 'Bay 4', 'ACTIVE', 'MB-5000H', 'Okuma', TRUE),
  ('LATHE-320', 'Mazak Quick Turn Lathe', 'WC-150', 'CNC Lathe', 'Turning', 'Bay 2', 'ACTIVE', 'Quick Turn 250', 'Mazak', TRUE)
ON CONFLICT (equipment_number) DO NOTHING;

-- Tool inventory
INSERT INTO tool_inventory (
  tool_id,
  material_id,
  tool_type,
  insert_type,
  insert_geometry,
  insert_grade,
  quantity_on_hand,
  min_quantity,
  unit_cost,
  supplier_name,
  active
) VALUES
  ('TL-ROUGH-4335', '11-00529', 'INSERT', 'ROUGHING', 'SNMG 4335', 'KC5010', 100, 25, 16.35, 'Sandvik', TRUE),
  ('TL-FINISH-2220', '11-00025', 'INSERT', 'FINISHING', 'SNMG 2220', 'KC5035', 75, 20, 16.71, 'Kennametal', TRUE)
ON CONFLICT (tool_id) DO NOTHING;

-- Measurement templates for CAT products
INSERT INTO measurement_templates (
  product_number,
  product_description,
  product_family,
  requires_barrel_diameter,
  barrel_diameter_target,
  barrel_diameter_tolerance,
  requires_flange_diameter,
  flange_diameter_target,
  flange_diameter_tolerance,
  requires_overall_length,
  overall_length_target,
  overall_length_tolerance,
  requires_length_to_flange,
  length_to_flange_target,
  length_to_flange_tolerance,
  od_measurement_count,
  id_measurement_count,
  length_measurement_count,
  measurement_instructions,
  critical_dimensions,
  special_requirements,
  volume_classification,
  measurement_frequency,
  priority_score,
  priority_label,
  active
) VALUES
  (
    'CAT536-6765',
    'Cylinder Casting - HIGHEST Priority',
    '536_SERIES',
    TRUE,
    11.569,
    0.02,
    TRUE,
    12.87,
    0.02,
    TRUE,
    59.519,
    0.02,
    TRUE,
    54.622,
    0.02,
    0,
    0,
    0,
    'Use measurement sheet 41A2360. Pi tape for ODs, calipers for lengths. All dimensions must pass before heat treat.',
    ARRAY['Barrel OD', 'Flange OD', 'Overall Length', 'Length to Flange'],
    'Heat treat approval requires PASS on all dimensions.',
    'Critical',
    'Each piece prior to heat treat',
    100,
    'HIGHEST PRIORITY',
    TRUE
  ),
  (
    'CAT536-6763',
    'Cylinder Casting - HIGH Priority',
    '536_SERIES',
    TRUE,
    11.569,
    0.02,
    TRUE,
    12.87,
    0.02,
    TRUE,
    59.519,
    0.02,
    TRUE,
    54.622,
    0.02,
    0,
    0,
    0,
    'Standard CAT 536 cylinder procedure. Verify barrel and flange diameters with Pi tape, confirm lengths with calibrated calipers.',
    ARRAY['Barrel OD', 'Flange OD', 'Overall Length', 'Length to Flange'],
    'Hold for review if any dimension trends toward marginal condition.',
    'High',
    'Each piece prior to heat treat',
    95,
    'HIGH PRIORITY',
    TRUE
  ),
  (
    'CAT536-6764',
    'Cylinder Casting - HIGH Priority',
    '536_SERIES',
    TRUE,
    11.569,
    0.02,
    TRUE,
    12.87,
    0.02,
    TRUE,
    59.519,
    0.02,
    TRUE,
    54.622,
    0.02,
    0,
    0,
    0,
    'Standard CAT 536 cylinder procedure. Confirm all OD and length features before releasing to heat treat.',
    ARRAY['Barrel OD', 'Flange OD', 'Overall Length', 'Length to Flange'],
    'Document any flange runout concerns prior to heat treat approval.',
    'High',
    'Each piece prior to heat treat',
    92,
    'HIGH PRIORITY',
    TRUE
  ),
  (
    'CAT150-3014',
    'Large Casting',
    'LARGE_CASTING',
    FALSE,
    NULL,
    NULL,
    FALSE,
    NULL,
    NULL,
    FALSE,
    NULL,
    NULL,
    FALSE,
    NULL,
    NULL,
    3,
    2,
    1,
    'Standard CAT product measurement procedures. Record all available dimensions. Focus on critical features.',
    ARRAY['Primary OD surfaces', 'Critical length datums', 'Bore alignments'],
    'Note porosity or inclusions before routing to downstream machining.',
    'Medium',
    'First-off and every 5 pieces',
    70,
    'MEDIUM PRIORITY',
    TRUE
  ),
  (
    'CAT150-3011',
    'Large Casting',
    'LARGE_CASTING',
    FALSE,
    NULL,
    NULL,
    FALSE,
    NULL,
    NULL,
    FALSE,
    NULL,
    NULL,
    FALSE,
    NULL,
    NULL,
    3,
    2,
    1,
    'Standard CAT product measurement procedures. Record all available dimensions. Focus on critical features.',
    ARRAY['OD machined surfaces', 'Datum lengths', 'Fixture points'],
    'Capture any surface defects or gating damage in notes.',
    'Medium',
    'First-off and every 5 pieces',
    68,
    'MEDIUM PRIORITY',
    TRUE
  ),
  (
    'CAT4T-6051',
    'Heavy Duty - HIGH Priority',
    'HEAVY_DUTY',
    FALSE,
    NULL,
    NULL,
    FALSE,
    NULL,
    NULL,
    FALSE,
    NULL,
    NULL,
    FALSE,
    NULL,
    NULL,
    3,
    2,
    1,
    'Standard CAT heavy-duty casting procedures. Confirm OD growth and flange flatness. Focus on machined datum surfaces.',
    ARRAY['Multiple OD steps', 'Flange surfaces', 'Datum lengths'],
    'Capture any cold shuts or heavy blast areas prior to machining.',
    'High',
    'Each piece prior to heat treat',
    80,
    'HIGH PRIORITY',
    TRUE
  ),
  (
    'CAT4T-5937',
    'Heavy Duty - HIGH Priority',
    'HEAVY_DUTY',
    FALSE,
    NULL,
    NULL,
    FALSE,
    NULL,
    NULL,
    FALSE,
    NULL,
    NULL,
    FALSE,
    NULL,
    NULL,
    3,
    2,
    1,
    'Standard CAT heavy-duty casting procedures. Confirm OD growth and flange flatness. Focus on machined datum surfaces.',
    ARRAY['Multiple OD steps', 'Flange surfaces', 'Datum lengths'],
    'Escalate if dimensional status trends marginal on consecutive pieces.',
    'High',
    'Each piece prior to heat treat',
    78,
    'HIGH PRIORITY',
    TRUE
  ),
  (
    'CAT4T-4774',
    'Heavy Duty - MEDIUM Priority',
    'HEAVY_DUTY',
    FALSE,
    NULL,
    NULL,
    FALSE,
    NULL,
    NULL,
    FALSE,
    NULL,
    NULL,
    FALSE,
    NULL,
    NULL,
    3,
    2,
    1,
    'Standard CAT heavy-duty casting procedures. Record OD and ID dimensions as available.',
    ARRAY['OD growth', 'ID bores', 'Overall length to datum'],
    'Highlight any porosity or surface inclusions.',
    'Medium',
    'First-off and every 3 pieces',
    60,
    'MEDIUM PRIORITY',
    TRUE
  ),
  (
    'CAT121-2077',
    'Large Assembly',
    'LARGE_ASSEMBLY',
    FALSE,
    NULL,
    NULL,
    FALSE,
    NULL,
    NULL,
    FALSE,
    NULL,
    NULL,
    FALSE,
    NULL,
    NULL,
    3,
    2,
    1,
    'Standard CAT assembly procedures. Capture OD, ID, and key lengths prior to release.',
    ARRAY['Assembly OD', 'Fixture interface lengths', 'Locating bores'],
    'Ensure locator pads are free from blast scale before inspection.',
    'Low',
    'Per lot',
    55,
    'STANDARD PRIORITY',
    TRUE
  ),
  (
    'CAT522-7552',
    'Large Assembly',
    'LARGE_ASSEMBLY',
    FALSE,
    NULL,
    NULL,
    FALSE,
    NULL,
    NULL,
    FALSE,
    NULL,
    NULL,
    FALSE,
    NULL,
    NULL,
    3,
    2,
    1,
    'Standard CAT assembly procedures. Capture OD, ID, and key lengths prior to release.',
    ARRAY['Assembly OD', 'Fixture interface lengths', 'Locating bores'],
    'Document any weld repair indications before progressing.',
    'Low',
    'Per lot',
    52,
    'STANDARD PRIORITY',
    TRUE
  )
ON CONFLICT (product_number) DO NOTHING;
